### ISSUE TITLE
TypeError: Option values must be strings with setuptools 19.1

### ISSUE THREAD

**Issue by lukasgraf** [buildout/buildout#283]
Since todays `19.1` release of `setuptools` buildout fails like this:

```
$ bin/buildout
...
While:
  Installing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 565, in install
    self._compute_part_signatures(install_parts)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 811, in _compute_part_signatures
    options['__buildout_signature__'] = ' '.join(sig)
  File "/var/lib/jenkins/zope/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'zc.recipe.egg-1.3.2-py2.7.egg setuptools-19.1-py2.7.egg zc.buildout-2.5.0-py2.7.egg')
```

Not sure whether this is an issue with `zc.buildout`, `setuptools`, or something else.

**Comment by Kilte** [comment]
Same issue

**Comment by jaraco** [comment]
I don't see anything in the code that implicates the changes in ez_setup.py. Can someone familiar with buildout provide an example that triggers the behavior?

I tried simply running `python bootstrap/bootstrap.py` from the repo, and that grabs setuptools 19.1 and runs without error, so there's something else going on.

**Comment by jaraco** [comment]
What does the buildout.cfg look like?

**Comment by jaraco** [comment]
I tried using https://travis-ci.org/bioidiap/bob.learn.em from the setuptools ticket, but it fails for other reasons on my box.

**Comment by siebenkopf** [comment]
Yes, ``bob.learn.em`` is part of a bigger project (Bob), which needs some installation.

However, any buildout.cfg should fail. Here is a small example:

```
[buildout]
parts = scripts
eggs = gridtk

extensions = bob.buildout

[scripts]
recipe = bob.buildout:scripts
```

BTW: I am not using ``bootstrap/bootstrap.py``, but ``bootstrap-buildout.py`` from https://bootstrap.pypa.io/bootstrap-buildout.py

**Comment by jaraco** [comment]
It's still working for me

```
$ mkdir bo283
$ cd bo283
$ cat > buildout.cfg
[buildout]
parts = scripts
eggs = gridtk

extensions = bob.buildout

[scripts]
recipe = bob.buildout:scripts
$ curl https://bootstrap.pypa.io/bootstrap-buildout.py -o - | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7458  100  7458    0     0  12183      0 --:--:-- --:--:-- --:--:-- 12186
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-19.1.zip
Extracting in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpgxf592vb
Now working in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpgxf592vb/setuptools-19.1
Building a Setuptools egg in /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/bootstrap-92rba8a0
/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/bootstrap-92rba8a0/setuptools-19.1-py3.5.egg
Creating directory '/Users/jaraco/Dropbox/code/main/setuptools/bo283/eggs'.
Creating directory '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin'.
Creating directory '/Users/jaraco/Dropbox/code/main/setuptools/bo283/parts'.
Creating directory '/Users/jaraco/Dropbox/code/main/setuptools/bo283/develop-eggs'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/buildout'.
$ bin/buildout
Getting distribution for 'bob.buildout'.
Got bob.buildout 2.0.9.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Got zc.recipe.egg 2.0.3.
Installing scripts.
Getting distribution for 'gridtk'.
zip_safe flag not set; analyzing archive contents...
Got gridtk 1.2.4.
Python: Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/python'.
GdbPython: Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/gdb-python'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/grid'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/qstat.py'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/jman'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/qdel.py'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/man.py'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/qsub.py'.
Getting distribution for 'nose'.
no previously-included directories found matching 'doc/.build'
Got nose 1.3.7.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/nosetests'.
Getting distribution for 'coverage'.
warning: no previously-included files found matching 'ci/appveyor.token'
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'tests/eggsrc/build'
no previously-included directories found matching 'tests/eggsrc/dist'
no previously-included directories found matching 'tests/eggsrc/*.egg-info'
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
ld: warning: ignoring file build/temp.macosx-10.6-intel-3.5/coverage/ctracer/datastack.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-3.5/coverage/ctracer/datastack.old: warning: 
ignoring file build/temp.macosx-10.6-intel-3.5/coverage/ctracer/filedisp.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-3.5/coverage/ctracer/filedisp.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-3.5/coverage/ctracer/module.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-3.5/coverage/ctracer/module.o
ld: warning: ignoring file build/temp.macosx-10.6-intel-3.5/coverage/ctracer/tracer.o, file was built for x86_64 which is not the architecture being linked (i386): build/temp.macosx-10.6-intel-3.5/coverage/ctracer/tracer.o
Got coverage 4.0.3.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/coverage'.
Getting distribution for 'sphinx'.
Got Sphinx 1.3.3.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/sphinx-apidoc'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/sphinx-build'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/sphinx-quickstart'.
Generated script '/Users/jaraco/Dropbox/code/main/setuptools/bo283/bin/sphinx-autogen'.
$ 
```

**Comment by siebenkopf** [comment]
Yep, python3 works. The issue is with python2.

**Comment by lukasgraf** [comment]
I'm also using Python 2 here. The `buildout.cfg` itself can be trivial:

```
$ wget 'https://bootstrap.pypa.io/bootstrap-buildout.py' 2>/dev/null
$ cat buildout.cfg
[buildout]
parts = foo

[foo]
recipe = zc.recipe.egg
$
$ python2.7 bootstrap-buildout.py
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-19.1.zip
Extracting in /var/folders/d5/8djs4qxd78lb98g8r7hyp7wr0000gn/T/tmpS_S6Uk
Now working in /var/folders/d5/8djs4qxd78lb98g8r7hyp7wr0000gn/T/tmpS_S6Uk/setuptools-19.1
Building a Setuptools egg in /var/folders/d5/8djs4qxd78lb98g8r7hyp7wr0000gn/T/bootstrap-2oxtMp
/var/folders/d5/8djs4qxd78lb98g8r7hyp7wr0000gn/T/bootstrap-2oxtMp/setuptools-19.1-py2.7.egg
Creating directory '/Users/lukasgraf/src/trivial-buildout/bin'.
Creating directory '/Users/lukasgraf/src/trivial-buildout/parts'.
Creating directory '/Users/lukasgraf/src/trivial-buildout/develop-eggs'.
Generated script '/Users/lukasgraf/src/trivial-buildout/bin/buildout'.
$
$ bin/buildout
While:
  Installing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "~/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "~/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 565, in install
    self._compute_part_signatures(install_parts)
  File "~/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 811, in _compute_part_signatures
    options['__buildout_signature__'] = ' '.join(sig)
  File "~/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'zc.recipe.egg-2.0.3-py2.7.egg setuptools-19.1-py2.7.egg zc.buildout-2.5.0-py2.7.egg')
```

**Comment by reinout** [comment]
The error message suggests that buildout doesn't like the unicode that is fed to an option. Apparently setuptools now returns it as unicode instead of strings.

**Comment by reinout** [comment]
I re-started a travis job and yes, it fails too. https://travis-ci.org/buildout/buildout/jobs/91337683

I'll try to whip up a quick pull request. If travis is happy, we're probably good.

**Comment by jamadden** [comment]
Is there a chance this is related to [setuptools issue 477](https://bitbucket.org/pypa/setuptools/issues/477) which in turn references the [issue 215](https://bitbucket.org/pypa/setuptools/issues/215) that changed in 19.1? They both seem to be unicode string related issues.

**Comment by reinout** [comment]
I've found the change in setuptools that triggered this: https://bitbucket.org/pypa/setuptools/commits/16007a2acbc5662238695f42d3d2ec1db09f0208 

`resolve_version()` downloads a json. What it gets out of it is nice and clean unicode. Which means the "I am setuptools 19.1" package name suddenly is unicode instead of ascii/bytestring because the "19.1" comes from json.

So... that's why we suddenly get unicode package name/versions back.

**Note**: I'm attempting a fix in #284. Please look at the code and review it because I want to release a new buildout version **Real Quick Now**.

**Comment by jamadden** [comment]
@reinout I think you're referencing the same thing I referenced above, which also causes trouble for ez_setup.py (setuptools 477). Would it be better to have this quickly fixed in setuptools? I think one of the setuptools devs has commented on this issue, and in general setuptools seems to release pretty quickly when needed.

**Comment by reinout** [comment]
**Fixed** by setuptools. No buildout release needed. See https://bitbucket.org/pypa/setuptools/issues/476/setuptools-191-breaks-zcbuildout

Hurray!

**Comment by lukasgraf** [comment]
Just in time before our Jenkins kicks off 300+ jobs at 2 AM :stuck_out_tongue_winking_eye: :tada: Thanks for your efforts in debugging this!

**Comment by reinout** [comment]
:-)

**Comment by erny** [comment]
I still get this error with seuptools 8.0 and running buildout -N for the second and following times (not the first). It would be nice so have some alternative comparison @ https://github.com/buildout/buildout/blob/master/src/zc/buildout/buildout.py#L1369

Regards.
