### ISSUE TITLE
[Question] buildout slows down problem 

### ISSUE THREAD

**Issue by mnjagadeesh** [buildout/buildout#573]
I am using 2.13.3 version buildout. It is noticed that as number of eggs grow, buildout slows down. Though exact version is mentioned downloading egg is very slow. Any idea to speed it up?

**Comment by goschtl** [comment]
You can try to run buildout -N it does not look for new versions....

**Comment by mnjagadeesh** [comment]
> You can try to run buildout -N it does not look for new versions....

Tried -N option but still feel slow. Also it is not reading ${buildout:download-cache} I downloaded few eggs into ${buildout:download-cache}/dist [also tried keeping thoe eggs in ${buildout:download-cache}] but still buildout downloading eggs.
This is interesting

**Comment by goschtl** [comment]
maybe you can try -vvv and see where it gets slow

**Comment by mnjagadeesh** [comment]
> maybe you can try -vvv and see where it gets slow

one one package has more than 10k eggs. that is taking time too much time.

**Comment by goschtl** [comment]
which one?

**Comment by mnjagadeesh** [comment]
> which one?

easy_install._obtain() method is taking time.  I have separate script to cache egg in downloads/dist. but buildout is not reading download-cache folder, but downloading eggs. Is there any flag to be used?

**Comment by goschtl** [comment]
can you show me your section i guess you use zc.recipe.egg? i will try it then

**Comment by mnjagadeesh** [comment]
> can you show me your section i guess you use zc.recipe.egg? i will try it then

Sure. I am using zc.recipe.egg. I will share configuration soon

**Comment by gotcha** [comment]
This sounds like an issue in `setuptools` that got solved in 46.3.0 : https://github.com/pypa/setuptools/pull/2108/

What is the version of `setuptools` that you use ?

**Comment by mnjagadeesh** [comment]
I am using setuptools version 44. I will upgrade and let you know

**Comment by nishantvarma** [comment]
I think this version is resolving this problem.

**Comment by mnjagadeesh** [comment]
> @gotcha/@mnjagadeesh , I think this fix is working as expected. I also observed slowness in the `hashcmp` function. Maybe `setuptools` can check for the exact version if the op is `==`, but that's OK for now.

Sure. Will check it and let you know. Thanks much for this update.

**Comment by mauritsvanrees** [comment]
Is slowness still a problem with current zc.buildout, pip, and setuptools versions?

**Comment by nishantvarma** [comment]
You can test it using this `test.cfg`:

```
[buildout]
parts = app
index = ${pkgserver:url}
download-cache = ${buildout:directory}/downloads
download-pkgs = ${buildout:download-cache}/dist

[app]
recipe = zc.recipe.egg
eggs =
        mypkg

[versions]
mypkg = 10.9.6

[pkgserver]
url = http://${:username}:${:password}@${:hostname}
hostname = packages.org
username = admin
password = pass
```

ran as `buildout -vv -c test.cfg`.

I have a package with thousands of releases. Before this fix, downloading it used to take around 5 hours. After the fix, it became significantly faster (the time I tested it). The current version seems a bit slow, but I can't say if it is simply due to more packages added or some new problem introduced.

One potential problem I can see is that it scans all available wheels before selecting which one to download—this results in a linear scan over all package versions.

**Comment by mnjagadeesh** [comment]
> [@mauritsvanrees](https://github.com/mauritsvanrees) , You can test it using this `test.cfg`:
> 
> ```
> [buildout]
> parts = app
> index = ${pkgserver:url}
> download-cache = ${buildout:directory}/downloads
> download-pkgs = ${buildout:download-cache}/dist
> 
> [app]
> recipe = zc.recipe.egg
> eggs =
>         mypkg
> 
> [versions]
> mypkg = 10.9.6
> 
> [pkgserver]
> url = http://${:username}:${:password}@${:hostname}
> hostname = packages.org
> username = user
> password = pass
> ```
> 
> ran as `buildout -vv -c test.cfg`.
> 
> I have a package with thousands of wheels. Before the fix, downloading took about 5 hours. After the fix, it improved significantly (~2–3 minutes IIRC). The current version feels slower, but it's unclear whether that's just due to the growing number of packages or a new issue introduced.
> 

> One possible issue is that it scans all the wheels i.e. O(n) before choosing which one to download—this might be the real problem. Hope it helps.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ yes. This is a real issue. Now with external script [with multi threads] I am caching all required packages. It is much faster now.

**Comment by mnjagadeesh** [comment]
> Is slowness still a problem with current zc.buildout, pip, and setuptools versions?

Yes, even after upgrading setuptools, it's still slow.
